name: "qyvx"
mode: "dev"
port: 8888
version: "v0.0.1"
start_time: "2024-08-26"
machine_id: 1

auth:
  jwt_expire: 8760

log:
  level: "debug"
  filename: "qyvx.log"
  max_size: 200
  max_age: 30
  max_backups: 7

# 数据库采用的是matrixone cloud提供的云端数据库,可直接链接(可以当作mysql使用)
mysql:
  host: xxx.cn-hangzhou.cluster.matrixonecloud.cn
  port: 6001
  user: xxx#admin#accountadmin
  password: "xxx"
  dbname: "xxx"
  max_open_conns: 200
  max_idle_conns: 50

#redis:
#  host: mo_redis
#  port: 6379
#  password: ""
#  db: 0
#  pool_size: 100
